import { ReactNode } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'

import { Card } from '@/components/Card'
import { NewTransactionModal } from '@/components/NewTransactionModal'
import axios from 'axios'
import { cookies } from 'next/headers'
import { DeleteTransactionModal } from '@/components/DeleteTransactionModal'
import { Providers } from '@/providers/providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface Summary {
  credit: number
  debit: number
  amount: number
}

export default async function RootLayout({
  children,
}: {
  children: ReactNode
}) {
  const sessionId = cookies().get('sessionId')?.value
  let summary: Summary | null = null

  if (sessionId) {
    const response = await axios.get(
      `https://transactions-api-rest-node.onrender.com/transactions/summary`,
      {
        withCredentials: true,
        headers: {
          Cookie: `sessionId=${sessionId}`,
        },
      },
    )

    summary = response.data.summary
  }

  return (
    <html lang="en">
      <body className={`${inter.className} h-screen w-screen bg-gray-100`}>
        <Providers>
          <NewTransactionModal />
          <DeleteTransactionModal />
          <header className="h-20 bg-cyan-800 pt-5 text-center text-2xl font-semibold text-white md:h-48">
            Finanças
          </header>
          <main className="mx-auto mt-5 max-w-[960px] md:mt-0 md:-translate-y-28">
            <div className="flex flex-col justify-between gap-10 px-5 md:flex-row lg:px-0">
              <Card type="credit" amount={summary ? summary.credit : 0} />
              <Card type="debit" amount={summary ? summary.debit : 0} />
              <Card type="total" amount={summary ? summary.amount : 0} />
            </div>
            <div className="mt-5 px-5 lg:px-0">{children}</div>
          </main>
        </Providers>
      </body>
    </html>
  )
}
